In [3]:
import numpy as np
np.arange(1,16).shape

(15,)

In [10]:
u = np.array([[6,0,3,6]]).transpose()
v = np.array([[4,2,1]])
print(u.shape)
print(v.shape)

np.matmul(u, v)

(4, 1)
(1, 3)


array([[24, 12,  6],
       [ 0,  0,  0],
       [12,  6,  3],
       [24, 12,  6]])

In [12]:
np.array([[5,0,7],[0,2,0],[4,0,0],[0,3,6]])

array([[5, 0, 7],
       [0, 2, 0],
       [4, 0, 0],
       [0, 3, 6]])

In [16]:
((5 - 24) ** 2 + (7 - 6) ** 2 + (2 - 0) ** 2 + (4 - 12) ** 2 + (3 - 12) ** 2 + (6 - 6) ** 2) / 2

255.5

In [19]:
(6 ** 2 + 3 ** 2 + 6 ** 2)/2 + (4 **2 + 2 ** 2 + 1 ** 2)/2

51.0

In [15]:
np.mean(loss)

1.25

In [16]:
sqrt_loss = np.vectorize(lambda x: x ** 2 / 2)

In [17]:
sqrt_loss(z)

array([0.   , 0.045, 0.045, 0.5  ])

In [18]:
np.mean(sqrt_loss(z))

0.1475