In [3]:
import numpy as np
b = np.arange(1,16).reshape(3,5)
print(b)
a = np.power(b, 2)
print(a)
c = np.array([[1,2,1],[3,4,1]])
d = np.array([1,1, 1])
print("#")
print(c)
print("---")
print(d.shape)
print("#")
m = c - d
print(m)
m == 0

d = np.array([1,3,4,5])
import scipy.sparse as sparse
sparse.coo_matrix(d, (np.arange(d.shape[0]), d))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]
#
[[1 2 1]
 [3 4 1]]
---
(3,)
#
[[0 1 0]
 [2 3 0]]


ModuleNotFoundError: No module named 'scipy'

In [10]:
u = np.array([[6,0,3,6]]).transpose()
v = np.array([[4,2,1]])
print(u.shape)
print(v.shape)

np.matmul(u, v)

(4, 1)
(1, 3)


array([[24, 12,  6],
       [ 0,  0,  0],
       [12,  6,  3],
       [24, 12,  6]])

In [12]:
np.array([[5,0,7],[0,2,0],[4,0,0],[0,3,6]])

array([[5, 0, 7],
       [0, 2, 0],
       [4, 0, 0],
       [0, 3, 6]])

In [16]:
((5 - 24) ** 2 + (7 - 6) ** 2 + (2 - 0) ** 2 + (4 - 12) ** 2 + (3 - 12) ** 2 + (6 - 6) ** 2) / 2

255.5

In [19]:
(6 ** 2 + 3 ** 2 + 6 ** 2)/2 + (4 **2 + 2 ** 2 + 1 ** 2)/2

51.0

In [15]:
np.mean(loss)

1.25

In [16]:
sqrt_loss = np.vectorize(lambda x: x ** 2 / 2)

In [17]:
sqrt_loss(z)

array([0.   , 0.045, 0.045, 0.5  ])

In [18]:
np.mean(sqrt_loss(z))

0.1475